### PR TITLE
Lint code; Add Steam Label More button; Add Offline button

### PR DESCRIPTION
**Pull request by Ash258**
- Linted all files
    - Spaces to tabs
    - Indentation fixes
    - ...
- Added **Achievement Label More** button (Style changes are welcome) (in d75be8764339dbd4a48dbe41dad16d8f94e94dce):
- Added **Offline** status button into menu (in 15cc0f96d44ca7b72b2215af4d2bd8b639fbfba8)

Button

## Few questions ❓❓

- `Steam/cached` folder could be linted too or is generated or something??
- Parentunlock/lockDialogs:
    - Should'nt that last place be inside layout block?

https://github.com/Outsetini/Air-for-Steam/blob/933ebbdbd6ad5c1aa48f297138ed1574a2f0b794/Resource/layout/parentallockdialog.layout#L14-L28
https://github.com/Outsetini/Air-for-Steam/blob/933ebbdbd6ad5c1aa48f297138ed1574a2f0b794/Resource/layout/parentalunlockdialog.layout#L20-L37

### CODE REVIEW

**Comment by Brottweiler** [comment]
>- Linted all files
>  - Spaces to tabs

Seriously? Using tabs or spaces is up to your own preference. Using spaces instead of tabs, or vice versa, isn't lint.

**Comment by Ash258** [comment]
> Indent all code via tabs rather than spaces.

https://github.com/Outsetini/Air-for-Steam#spacing

**Comment by Brottweiler** [comment]
@Ash258 Well, my bad. I would've thought the entire project already was tabs if that was the rules.

**Comment by Outsetini** [comment]
Whoa, this is huge man, thanks a bunch. Also, you are correct on the lock/unlockdialogues, those should be within the layout block. I'll fix that up.

**Pull request merged**
