### PR TITLE
Rollback Steam Blue Styles

### PR DESCRIPTION
**Pull request by lKobi**
- Vanilla Steam Blue values.

### CODE REVIEW

**Comment by sebie** [comment]
Because there is demand for the 'new' blue theme, I do not think we should completely remove it. Instead maybe offer two blue themes?

And in any case, offer screenshots (on imgur?) of all the new themes.

/cc: #125

**Comment by lKobi** [comment]
The normal Steam Blue should have never been overwritten, and the guy who did it shouldn't have claimed the created Steam Blue.

We had the Steam Blue for over a year, and got overwritten by the new theme, the new one doesn't fit the steam styles at all compared to the old one.

What we need is Steam Blue back, and the guy who overwritten that theme should get a new name for his theme instead of claiming there was no Steam Blue.

**Comment by Outsetini** [comment]
This was my bad, I made the changes to match the new blue theme without thinking about the consequences. I'll revert the original Steam Blue theme and create a new focus theme for the new blue.

**Comment by Outsetini** [comment]
https://github.com/Outsetini/Air-for-Steam/commit/afcad9fd59e83e91515888b34519d2f11fe37218

**Pull request closed without merging**
