### PR TITLE
Add Pixel Dark theme

### PR DESCRIPTION
**Pull request by snowtyler**

### CODE REVIEW

**Comment by Outsetini** [comment]
Hey @snowtyler, could you provide a quick screenshot of the theme? Thanks!

**Comment by snowtyler** [comment]
It'll be a while. I'm on vacation right now.

**Comment by CorruptComputer** [comment]
@Outsetini I just downloaded and checked:

image

Also I might add, this ONLY works with the dark theme, however there is no reason for it to. Changing the background color manually, it actually looks pleasant both ways.

**Comment by CorruptComputer** [comment]
@Outsetini Version with all 4 Google colors: 
image

Also works with the light theme (although I prefer the dark):
image

My edited `pixel.styles`:
````
resource/colors/user/pixel.styles {

		// 66 133 244  blue
		// 15 157 88  green
		// 244 180 0  yellow
		// 219 68 55  red
	colors {
		Focus="66 133 244 255" 
		Focus2="244 180 0 255" 
		Focus3="15 157 88 255" 
		Focus4="15 157 88 150" 
		A2TextFocus="219 68 55 255"
		A2TextFocusHover="Focus2"

        //THEME OVERRIDES
        A2Scroll "244 180 0 255"
        A2ScrollHover "244 200 20 255"

	}
}
````

I wasn't quite sure what `A2TextFocusHover` did, as changing it seemed to have no effect.

**Comment by snowtyler** [comment]
It's named pixel because it uses the colors found in the pixel system UI.

**Comment by CorruptComputer** [comment]
Ah, well I think you should look at the name some more. Because in most android development when people call things "pixel" it usually means they include all four colors. Although this isn't android it could still lead to confusion. Maybe "pixel blue"?

**Comment by Outsetini** [comment]
Thanks for the contributions guys. I've went ahead and merged your pixel dark theme @snowtyler and it'll be included in the next official release!

@CorruptComputer I've also added your suggested theme, but for the ease of understandability I've named it "google" instead. Seems appropriate enough, yes? Let me know if you have any problems, and otherwise it's looking good. 👍

**Pull request merged**
