### PR TITLE
Settings Revamp

### LINKED ISSUE #172: Overlapping text in interface settings (Beta Client)
With the latest beta update ( http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1660013740954795957 ), Valve added a check to disable dpi scaling (for windows 10 only it seems) which created overlapping text with this check ( DPIScalingCheck ). I'm unsure if the overlapping selection at the top is related to that.
steam_2018-03-24_17-00-26
I was able to partly solve this by putting 'DPIScalingCheck' in "[Air folder]\Steam\cached\SettingsSubInterface.res" but it doesn't solve everything
 `		place {
			control=AutoLaunchCheck,BigPictureModeCheck,UrlBarCheck,DWriteCheck,DPIScalingCheck,H264HWAccelCheck
			dir=down start=SkinCombo y=20
		}`
image

### PR DESCRIPTION
**Pull request by StaticRocket**
Fixes #172 by adding DPIScalingCheck updating the label for `FavoriteWindowCombo` which was recently changed from `Label2` to `Label1`, as observed in the default steam skin cached settings page. For whatever reason none of the other labels were touched. This also integrates `TranslationLabel` and the, now, three dividers for that page instead of annihilating them.
image
image
image

### CODE REVIEW

**Comment by Outsetini** [comment]
Oh shoot, hey man, sorry I didn't notice the pull request until I had already fixed the interface/shader settings issues. Doh. Thanks for the contribution though, I do appreciate the assistance. :)

**Comment by StaticRocket** [comment]
image

**Comment by StaticRocket** [comment]
I think you should look at some of my other changes. At least, the revamped downloads page, I get it if you dislike my Friends tab rework. There were a lot of updates labeled "Syntax" as I was trying to get my stuff to match your formatting and inforce your formatting globally. There were multiple pages that were set up like:
```
/address/of/file/here {

  styles {
    blah=blah
  }

  format {
  place { control=blah }
  }
```
And also pages set up like steams default layout files:
```
"/address/of/file/here"
{
  styles
  {
    blah=blah
  }

  format
  {
    place { control=blah }
  }
}
```
It was hard to figure out what you wanted things to look like, but I have a tendency to nitpick these things, so... Eh.

**Comment by Outsetini** [comment]
It was definitely my intention to bring all the files to a more consistent layout like the first one. I sorta gave up hope in having everything as well laid out as I wished it could be though, Steam just isn't coded well enough to allow for good code consistency. Alas. I decided to just keep my energy focused on things that everyone can see and appreciate, while not going too much out of my way to spend time organizing things I'll only ever see.

**Pull request closed without merging**
