### PR TITLE
Added full support for Mac

### PR DESCRIPTION
**Pull request by novovnz**
I've implemented full macOS support for Air. Changes include:
* Adds correct mac close/max/min icons
* Moves said icons to the left for all windows
* Adjusts spacing for items around the icons

All items are designated with `[$OSX]` and `[!$OSX]` / `[$WINDOWS||LINUX]` so the UI should operate the same as previously for Windows/Linux

### CODE REVIEW

**Comment by Outsetini** [comment]
Woah! These are some pretty beefy additions, thanks for tackling this @novovnz! Any chance you could post a screenshot or two? I don't have a mac to preview it on, but I'd love to see how it looks. :)

**Comment by novovnz** [comment]
Looks like this:
![this]
(http://i.imgur.com/ErTkacx.png)

**Comment by sebie** [comment]
Double woah. :open_mouth: The close/minimize/maximize buttons look great! 

Great job!

**Comment by Outsetini** [comment]
Cool stuff, I'll go ahead and merge the request see what the Mac crowd thinks!

**Comment by yashendra2797** [comment]
Holy hell! Finally! Thank you so much! Gonna see if this works.

**Comment by Outsetini** [comment]
I'm putting out a release today, just got a little behind on official releases. Sorry about that!

**Comment by yashendra2797** [comment]
Became a $1 patron to show my appreciation. Been waiting for this for a *long* time. Ironic that this happens a week before I get my PC. 😂 

@Outsetini Is it okay to create a new Issue for some visual enhancements? Or should I just PM you?

**Comment by Outsetini** [comment]
@yashendra2797 Creating an issue is probably easier to track. I can't guarantee that I can fix any Mac-specific issues since I only have my PC though. Happy to pull in any changes if you or anyone else can contribute though!

And thanks for your patreon support, much appreciated!

**Pull request merged**
