### PR TITLE
Fixed the new button in beta and added 'Invisible' status to menu

### PR DESCRIPTION
**Pull request by f0rb1d**

### CODE REVIEW

**Comment by f0rb1d** [comment]
Preview:
Air-For-Steam-Fixed

**Comment by cr1ogen** [comment]
how i can apply this fix? Thank you!!

**Comment by f0rb1d** [comment]
@cr1ogen Do a git clone my repo [https://github.com/f0rb1d/Air-for-Steam]

**Comment by DrManhattvn** [comment]
Awesome work. I am trying to get rid of those two hidden/invisible buttons (which are part of the new UI)
https://i.imgur.com/Pee7Kh8.png

I marked them with Steam's VGUI and got this:
https://imgur.com/a/432dURY

Since I am new at this, do you or anybody knows how to remove them from the Air's UI?

Regards.

**Comment by conrev** [comment]
I see that invoking "View Friends List" from the dropdown UI doesnt close the dropdown menu, and the dropdown menu got stuck until i opened it again. Is this the intended behavior or it's a bug?

**Comment by f0rb1d** [comment]
@DrManhattvn 
As a beginner themer, I think there is no way to remove the buttons. But moving them to better places is possible.

@conrev 
The configuration about the button is extracted from official files, so I think it is INTENDED. But it can be fixed.

**Comment by wowweemip-fan** [comment]
How do I get this update?

**Comment by StaticRocket** [comment]
@wowweemip-fan
*View the pull requests source branch
*Download the zip
*Unzip and apply like it's a new skin

Or do a git clone (which was mentioned above), to skip the unzipping step.

**Comment by StaticRocket** [comment]
This skin needs new icons made for the announcement button to support different hover/click states and this patchin particular still leaves a few buttons in odd places. I recommend looking at the default Steam\resource\layout\steamrootdialog.layout file, which lists the various controls. Here's the list as it is so far:
- [x] fullscreen
- [x] startvr
- [x] exitvr
- [x] UINavigatorPanel
- [x] UIStatusPanel
- [x] MenuBar
- [x] SupportAlert
- [ ] XPVistaAlert
- [x] ParentalLockButton
- [x] InboxButton
- [ ] AnnouncementButton
- [X] AccountButton
- [x] add_game
- [ ] frame_title
- [ ] universe_label
- [ ] view_friends
---
Note: Any item not checked is placed in it's default location, which is usually behind another button, which can pose some problems. Outsetini normally sets unused controls to have 0 width and 0 height. I was going to submit a PR to address these controls in your fork, but never got around to it.

**Comment by Outsetini** [comment]
Thanks for the preliminary work on this fellas!

**Pull request merged**
