### PR TITLE
New inbox active image

### PR DESCRIPTION
**Pull request by leskal**
Change active inbox from white to orange to different from the inbox ixon

### CODE REVIEW

**Comment by Spidersouris** [comment]
+1. Actually, you can't know if you received a notification or not without clicking the flag.

**Comment by sebie** [comment]
@leskal: I have I assigned the PR to @Outsetini. 
A possible issue could be a color conflict with "[happyorange](https://github.com/Outsetini/Air-for-Steam/blob/master/config.ini#L42)" style contributed Xanoxis, though I have not tested that.

@Spidersouris: thanks for the screenshot! Definitely makes it easier to see the changes, without downloading.

**Comment by Spidersouris** [comment]
Here's how it looks like with the happyorange style:

Preview

**Comment by leskal** [comment]
Can you check the new flag?

**Comment by Spidersouris** [comment]
w/ the newest flag

Preview

**Comment by Outsetini** [comment]
I'd rather avoid using color cues in this situation, but I decided to try updating the icon to the material design bell notification icon. Give the latest version a pull and let me know what you guys think.
capture

**Comment by leskal** [comment]
Much better :)

**Pull request closed without merging**
